name: vpn_osin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  drift: ^2.34.2
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.3.1
  google_fonts: ^8.1.0
  path: ^1.9.1
  path_provider: ^2.1.6
  sqlite3: ^3.4.0
  sqlite3_flutter_libs: ^0.5.42

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.15.1
  drift_dev: 2.34.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  pigeon: ^27.1.1
  very_good_analysis: ^10.3.0

hooks:
  user_defines:
    sqlite3:
      source: sqlite3mc

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
