// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum VpnStatusMessage: Int, CaseIterable {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case disconnecting = 3
  case error = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct VpnConfigMessage: Hashable, CustomStringConvertible {
  var host: String
  var port: Int64
  var userId: String
  var serverName: String
  var singboxConfigJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VpnConfigMessage? {
    let host = pigeonVar_list[0] as! String
    let port = pigeonVar_list[1] as! Int64
    let userId = pigeonVar_list[2] as! String
    let serverName = pigeonVar_list[3] as! String
    let singboxConfigJson = pigeonVar_list[4] as! String

    return VpnConfigMessage(
      host: host,
      port: port,
      userId: userId,
      serverName: serverName,
      singboxConfigJson: singboxConfigJson
    )
  }
  func toList() -> [Any?] {
    return [
      host,
      port,
      userId,
      serverName,
      singboxConfigJson,
    ]
  }
  static func == (lhs: VpnConfigMessage, rhs: VpnConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.host, rhs.host) && MessagesPigeonInternal.deepEquals(lhs.port, rhs.port) && MessagesPigeonInternal.deepEquals(lhs.userId, rhs.userId) && MessagesPigeonInternal.deepEquals(lhs.serverName, rhs.serverName) && MessagesPigeonInternal.deepEquals(lhs.singboxConfigJson, rhs.singboxConfigJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VpnConfigMessage")
    MessagesPigeonInternal.deepHash(value: host, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: port, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: serverName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: singboxConfigJson, hasher: &hasher)
  }

  public var description: String {
    return "VpnConfigMessage(host: \(String(describing: host)), port: \(String(describing: port)), userId: \(String(describing: userId)), serverName: \(String(describing: serverName)), singboxConfigJson: \(String(describing: singboxConfigJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VpnStatusSnapshotMessage: Hashable, CustomStringConvertible {
  var status: VpnStatusMessage
  var connectedSinceEpochMs: Int64? = nil
  var rxBytes: Int64
  var txBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VpnStatusSnapshotMessage? {
    let status = pigeonVar_list[0] as! VpnStatusMessage
    let connectedSinceEpochMs: Int64? = nilOrValue(pigeonVar_list[1])
    let rxBytes = pigeonVar_list[2] as! Int64
    let txBytes = pigeonVar_list[3] as! Int64

    return VpnStatusSnapshotMessage(
      status: status,
      connectedSinceEpochMs: connectedSinceEpochMs,
      rxBytes: rxBytes,
      txBytes: txBytes
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      connectedSinceEpochMs,
      rxBytes,
      txBytes,
    ]
  }
  static func == (lhs: VpnStatusSnapshotMessage, rhs: VpnStatusSnapshotMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.connectedSinceEpochMs, rhs.connectedSinceEpochMs) && MessagesPigeonInternal.deepEquals(lhs.rxBytes, rhs.rxBytes) && MessagesPigeonInternal.deepEquals(lhs.txBytes, rhs.txBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VpnStatusSnapshotMessage")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connectedSinceEpochMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rxBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: txBytes, hasher: &hasher)
  }

  public var description: String {
    return "VpnStatusSnapshotMessage(status: \(String(describing: status)), connectedSinceEpochMs: \(String(describing: connectedSinceEpochMs)), rxBytes: \(String(describing: rxBytes)), txBytes: \(String(describing: txBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol VpnEventMessage {

}

/// Generated class from Pigeon that represents data sent in messages.
struct StatusChangedMessage: VpnEventMessage {
  var status: VpnStatusMessage
  var connectedSinceEpochMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StatusChangedMessage? {
    let status = pigeonVar_list[0] as! VpnStatusMessage
    let connectedSinceEpochMs: Int64? = nilOrValue(pigeonVar_list[1])

    return StatusChangedMessage(
      status: status,
      connectedSinceEpochMs: connectedSinceEpochMs
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      connectedSinceEpochMs,
    ]
  }
  static func == (lhs: StatusChangedMessage, rhs: StatusChangedMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.connectedSinceEpochMs, rhs.connectedSinceEpochMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StatusChangedMessage")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connectedSinceEpochMs, hasher: &hasher)
  }

  public var description: String {
    return "StatusChangedMessage(status: \(String(describing: status)), connectedSinceEpochMs: \(String(describing: connectedSinceEpochMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LogMessage: VpnEventMessage {
  var text: String
  var timestampMillis: Int64
  var level: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LogMessage? {
    let text = pigeonVar_list[0] as! String
    let timestampMillis = pigeonVar_list[1] as! Int64
    let level = pigeonVar_list[2] as! String

    return LogMessage(
      text: text,
      timestampMillis: timestampMillis,
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      timestampMillis,
      level,
    ]
  }
  static func == (lhs: LogMessage, rhs: LogMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.timestampMillis, rhs.timestampMillis) && MessagesPigeonInternal.deepEquals(lhs.level, rhs.level)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LogMessage")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestampMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
  }

  public var description: String {
    return "LogMessage(text: \(String(describing: text)), timestampMillis: \(String(describing: timestampMillis)), level: \(String(describing: level)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrafficChangedMessage: VpnEventMessage {
  var rxBytes: Int64
  var txBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrafficChangedMessage? {
    let rxBytes = pigeonVar_list[0] as! Int64
    let txBytes = pigeonVar_list[1] as! Int64

    return TrafficChangedMessage(
      rxBytes: rxBytes,
      txBytes: txBytes
    )
  }
  func toList() -> [Any?] {
    return [
      rxBytes,
      txBytes,
    ]
  }
  static func == (lhs: TrafficChangedMessage, rhs: TrafficChangedMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.rxBytes, rhs.rxBytes) && MessagesPigeonInternal.deepEquals(lhs.txBytes, rhs.txBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TrafficChangedMessage")
    MessagesPigeonInternal.deepHash(value: rxBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: txBytes, hasher: &hasher)
  }

  public var description: String {
    return "TrafficChangedMessage(rxBytes: \(String(describing: rxBytes)), txBytes: \(String(describing: txBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ErrorMessage: VpnEventMessage {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return ErrorMessage(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: ErrorMessage, rhs: ErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "ErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VpnStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return VpnConfigMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return VpnStatusSnapshotMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return StatusChangedMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return LogMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return TrafficChangedMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return ErrorMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VpnStatusMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VpnConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VpnStatusSnapshotMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? StatusChangedMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? LogMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? TrafficChangedMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ErrorMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VpnHostApi {
  func startVpn(config: VpnConfigMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func stopVpn(completion: @escaping (Result<Void, Error>) -> Void)
  func getStatus() throws -> VpnStatusSnapshotMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VpnHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VpnHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VpnHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_oko.VpnHostApi.startVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startVpnChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! VpnConfigMessage
        api.startVpn(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startVpnChannel.setMessageHandler(nil)
    }
    let stopVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_oko.VpnHostApi.stopVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopVpnChannel.setMessageHandler { _, reply in
        api.stopVpn { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopVpnChannel.setMessageHandler(nil)
    }
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_oko.VpnHostApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class VpnEventsStreamHandler: PigeonEventChannelWrapper<VpnEventMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: VpnEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.vpn_oko.VpnEventsApi.vpnEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<VpnEventMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
