// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum VpnStatusMessage {
  disconnected,
  connecting,
  connected,
  disconnecting,
  error,
}

class VpnConfigMessage {
  VpnConfigMessage({
    required this.host,
    required this.port,
    required this.userId,
    required this.serverName,
    required this.singboxConfigJson,
  });

  String host;

  int port;

  String userId;

  String serverName;

  String singboxConfigJson;

  List<Object?> _toList() {
    return <Object?>[
      host,
      port,
      userId,
      serverName,
      singboxConfigJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnConfigMessage decode(Object result) {
    result as List<Object?>;
    return VpnConfigMessage(
      host: result[0]! as String,
      port: result[1]! as int,
      userId: result[2]! as String,
      serverName: result[3]! as String,
      singboxConfigJson: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(host, other.host) && _deepEquals(port, other.port) && _deepEquals(userId, other.userId) && _deepEquals(serverName, other.serverName) && _deepEquals(singboxConfigJson, other.singboxConfigJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnConfigMessage(host: $host, port: $port, userId: $userId, serverName: $serverName, singboxConfigJson: $singboxConfigJson)';
  }
}

class VpnStatusSnapshotMessage {
  VpnStatusSnapshotMessage({
    required this.status,
    this.connectedSinceEpochMs,
    required this.rxBytes,
    required this.txBytes,
    this.sessionEndsAtEpochMs,
    this.cooldownUntilEpochMs,
  });

  VpnStatusMessage status;

  int? connectedSinceEpochMs;

  int rxBytes;

  int txBytes;

  int? sessionEndsAtEpochMs;

  int? cooldownUntilEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      status,
      connectedSinceEpochMs,
      rxBytes,
      txBytes,
      sessionEndsAtEpochMs,
      cooldownUntilEpochMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnStatusSnapshotMessage decode(Object result) {
    result as List<Object?>;
    return VpnStatusSnapshotMessage(
      status: result[0]! as VpnStatusMessage,
      connectedSinceEpochMs: result[1] as int?,
      rxBytes: result[2]! as int,
      txBytes: result[3]! as int,
      sessionEndsAtEpochMs: result[4] as int?,
      cooldownUntilEpochMs: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnStatusSnapshotMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(connectedSinceEpochMs, other.connectedSinceEpochMs) && _deepEquals(rxBytes, other.rxBytes) && _deepEquals(txBytes, other.txBytes) && _deepEquals(sessionEndsAtEpochMs, other.sessionEndsAtEpochMs) && _deepEquals(cooldownUntilEpochMs, other.cooldownUntilEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnStatusSnapshotMessage(status: $status, connectedSinceEpochMs: $connectedSinceEpochMs, rxBytes: $rxBytes, txBytes: $txBytes, sessionEndsAtEpochMs: $sessionEndsAtEpochMs, cooldownUntilEpochMs: $cooldownUntilEpochMs)';
  }
}

sealed class VpnEventMessage {
}

class StatusChangedMessage extends VpnEventMessage {
  StatusChangedMessage({
    required this.status,
    this.connectedSinceEpochMs,
  });

  VpnStatusMessage status;

  int? connectedSinceEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      status,
      connectedSinceEpochMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static StatusChangedMessage decode(Object result) {
    result as List<Object?>;
    return StatusChangedMessage(
      status: result[0]! as VpnStatusMessage,
      connectedSinceEpochMs: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StatusChangedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(connectedSinceEpochMs, other.connectedSinceEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StatusChangedMessage(status: $status, connectedSinceEpochMs: $connectedSinceEpochMs)';
  }
}

class LogMessage extends VpnEventMessage {
  LogMessage({
    required this.text,
    required this.timestampMillis,
    required this.level,
  });

  String text;

  int timestampMillis;

  String level;

  List<Object?> _toList() {
    return <Object?>[
      text,
      timestampMillis,
      level,
    ];
  }

  Object encode() {
    return _toList();  }

  static LogMessage decode(Object result) {
    result as List<Object?>;
    return LogMessage(
      text: result[0]! as String,
      timestampMillis: result[1]! as int,
      level: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LogMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) && _deepEquals(timestampMillis, other.timestampMillis) && _deepEquals(level, other.level);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LogMessage(text: $text, timestampMillis: $timestampMillis, level: $level)';
  }
}

class TrafficChangedMessage extends VpnEventMessage {
  TrafficChangedMessage({
    required this.rxBytes,
    required this.txBytes,
  });

  int rxBytes;

  int txBytes;

  List<Object?> _toList() {
    return <Object?>[
      rxBytes,
      txBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrafficChangedMessage decode(Object result) {
    result as List<Object?>;
    return TrafficChangedMessage(
      rxBytes: result[0]! as int,
      txBytes: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrafficChangedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rxBytes, other.rxBytes) && _deepEquals(txBytes, other.txBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrafficChangedMessage(rxBytes: $rxBytes, txBytes: $txBytes)';
  }
}

class ErrorMessage extends VpnEventMessage {
  ErrorMessage({
    required this.code,
    required this.message,
  });

  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static ErrorMessage decode(Object result) {
    result as List<Object?>;
    return ErrorMessage(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ErrorMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ErrorMessage(code: $code, message: $message)';
  }
}

class DemoExpiredMessage extends VpnEventMessage {
  DemoExpiredMessage({
    required this.cooldownUntilEpochMs,
  });

  int cooldownUntilEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      cooldownUntilEpochMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static DemoExpiredMessage decode(Object result) {
    result as List<Object?>;
    return DemoExpiredMessage(
      cooldownUntilEpochMs: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DemoExpiredMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cooldownUntilEpochMs, other.cooldownUntilEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DemoExpiredMessage(cooldownUntilEpochMs: $cooldownUntilEpochMs)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VpnStatusMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VpnConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is VpnStatusSnapshotMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is StatusChangedMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is LogMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is TrafficChangedMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ErrorMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is DemoExpiredMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnStatusMessage.values[value];
      case 130:
        return VpnConfigMessage.decode(readValue(buffer)!);
      case 131:
        return VpnStatusSnapshotMessage.decode(readValue(buffer)!);
      case 132:
        return StatusChangedMessage.decode(readValue(buffer)!);
      case 133:
        return LogMessage.decode(readValue(buffer)!);
      case 134:
        return TrafficChangedMessage.decode(readValue(buffer)!);
      case 135:
        return ErrorMessage.decode(readValue(buffer)!);
      case 136:
        return DemoExpiredMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class VpnHostApi {
  /// Constructor for [VpnHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpnHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startVpn(VpnConfigMessage config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_osin.VpnHostApi.startVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopVpn() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_osin.VpnHostApi.stopVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<VpnStatusSnapshotMessage> getStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_osin.VpnHostApi.getStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VpnStatusSnapshotMessage;
  }
}

/// Returns a broadcast [Stream] of events from the `vpnEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<VpnEventMessage> vpnEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel vpnEventsChannel =
      EventChannel('dev.flutter.pigeon.vpn_osin.VpnEventsApi.vpnEvents$instanceName', pigeonMethodCodec);
  return vpnEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as VpnEventMessage;
  });
}
    
