// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.vpn_osin.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class VpnStatusMessage(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): VpnStatusMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnConfigMessage (
  val host: String,
  val port: Long,
  val userId: String,
  val serverName: String,
  val singboxConfigJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnConfigMessage {
      val host = pigeonVar_list[0] as String
      val port = pigeonVar_list[1] as Long
      val userId = pigeonVar_list[2] as String
      val serverName = pigeonVar_list[3] as String
      val singboxConfigJson = pigeonVar_list[4] as String
      return VpnConfigMessage(host, port, userId, serverName, singboxConfigJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      host,
      port,
      userId,
      serverName,
      singboxConfigJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnConfigMessage
    return MessagesPigeonUtils.deepEquals(this.host, other.host) && MessagesPigeonUtils.deepEquals(this.port, other.port) && MessagesPigeonUtils.deepEquals(this.userId, other.userId) && MessagesPigeonUtils.deepEquals(this.serverName, other.serverName) && MessagesPigeonUtils.deepEquals(this.singboxConfigJson, other.singboxConfigJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.host)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.port)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serverName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.singboxConfigJson)
    return result
  }
  override fun toString(): String {
    return "VpnConfigMessage(host=$host, port=$port, userId=$userId, serverName=$serverName, singboxConfigJson=$singboxConfigJson)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnStatusSnapshotMessage (
  val status: VpnStatusMessage,
  val connectedSinceEpochMs: Long? = null,
  val rxBytes: Long,
  val txBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnStatusSnapshotMessage {
      val status = pigeonVar_list[0] as VpnStatusMessage
      val connectedSinceEpochMs = pigeonVar_list[1] as Long?
      val rxBytes = pigeonVar_list[2] as Long
      val txBytes = pigeonVar_list[3] as Long
      return VpnStatusSnapshotMessage(status, connectedSinceEpochMs, rxBytes, txBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      connectedSinceEpochMs,
      rxBytes,
      txBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnStatusSnapshotMessage
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.connectedSinceEpochMs, other.connectedSinceEpochMs) && MessagesPigeonUtils.deepEquals(this.rxBytes, other.rxBytes) && MessagesPigeonUtils.deepEquals(this.txBytes, other.txBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectedSinceEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rxBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.txBytes)
    return result
  }
  override fun toString(): String {
    return "VpnStatusSnapshotMessage(status=$status, connectedSinceEpochMs=$connectedSinceEpochMs, rxBytes=$rxBytes, txBytes=$txBytes)"
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class VpnEventMessage 
/** Generated class from Pigeon that represents data sent in messages. */
data class StatusChangedMessage (
  val status: VpnStatusMessage,
  val connectedSinceEpochMs: Long? = null
) : VpnEventMessage()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusChangedMessage {
      val status = pigeonVar_list[0] as VpnStatusMessage
      val connectedSinceEpochMs = pigeonVar_list[1] as Long?
      return StatusChangedMessage(status, connectedSinceEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      connectedSinceEpochMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatusChangedMessage
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.connectedSinceEpochMs, other.connectedSinceEpochMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectedSinceEpochMs)
    return result
  }
  override fun toString(): String {
    return "StatusChangedMessage(status=$status, connectedSinceEpochMs=$connectedSinceEpochMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrafficChangedMessage (
  val rxBytes: Long,
  val txBytes: Long
) : VpnEventMessage()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrafficChangedMessage {
      val rxBytes = pigeonVar_list[0] as Long
      val txBytes = pigeonVar_list[1] as Long
      return TrafficChangedMessage(rxBytes, txBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rxBytes,
      txBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrafficChangedMessage
    return MessagesPigeonUtils.deepEquals(this.rxBytes, other.rxBytes) && MessagesPigeonUtils.deepEquals(this.txBytes, other.txBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rxBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.txBytes)
    return result
  }
  override fun toString(): String {
    return "TrafficChangedMessage(rxBytes=$rxBytes, txBytes=$txBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ErrorMessage (
  val code: String,
  val message: String
) : VpnEventMessage()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ErrorMessage {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return ErrorMessage(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ErrorMessage
    return MessagesPigeonUtils.deepEquals(this.code, other.code) && MessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "ErrorMessage(code=$code, message=$message)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnStatusMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnStatusSnapshotMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusChangedMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrafficChangedMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VpnStatusMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VpnConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VpnStatusSnapshotMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is StatusChangedMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TrafficChangedMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ErrorMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VpnHostApi {
  fun startVpn(config: VpnConfigMessage, callback: (Result<Unit>) -> Unit)
  fun stopVpn(callback: (Result<Unit>) -> Unit)
  fun getStatus(): VpnStatusSnapshotMessage

  companion object {
    /** The codec used by VpnHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VpnHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VpnHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_osin.VpnHostApi.startVpn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as VpnConfigMessage
            api.startVpn(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_osin.VpnHostApi.stopVpn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopVpn{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_osin.VpnHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class VpnEventsStreamHandler : MessagesPigeonEventChannelWrapper<VpnEventMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: VpnEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.vpn_osin.VpnEventsApi.vpnEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<VpnEventMessage>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<VpnEventMessage>) {}

override fun onCancel(p0: Any?) {}
}
      
